import sharp from "sharp";
import potrace from "potrace";
import fs from "node:fs";

const src = "public/logo/merovi-mark.png";

const { data, info } = await sharp(src)
  .flatten({ background: "#000000" })
  .negate()
  .png()
  .toBuffer({ resolveWithObject: true });

console.log("traced source size:", info.width, info.height);

potrace.trace(
  data,
  {
    threshold: 128,
    turdSize: 5,
    optCurve: true,
    optTolerance: 0.3,
  },
  (err, svg) => {
    if (err) throw err;
    const match = svg.match(/<path[^>]*\sd="([^"]+)"/);
    if (!match) throw new Error("no path found in traced svg");
    const d = match[1];
    const out = `// Auto-generated by scripts/trace-logo.mjs from public/logo/merovi-mark.png.
// Re-run the script if the source logo asset changes.
export const LOGO_PATH_D = ${JSON.stringify(d)};
export const LOGO_PATH_VIEWBOX = { width: ${info.width}, height: ${info.height} };
`;
    fs.writeFileSync("components/3d/logo-path.ts", out);
    console.log("wrote components/3d/logo-path.ts");
  },
);
